Ben: OneZero task
onezero-team/veahavta-task pull request #4
Opened 2022-04-25 18:08 UTC by bendan7

2022-04-25 19:40 UTC, omrirz requested changes
1. Links are not clickable
<img width="274" alt="Screen Shot 2022-04-25 at 21 57 48" src="https://user-images.githubusercontent.com/13974474/165156984-1817bf6c-9804-455c-a3c0-5b5dc75a8d5a.png">
<img width="553" alt="Screen Shot 2022-04-25 at 21 58 12" src="https://user-images.githubusercontent.com/13974474/165156989-8c41bb28-df8c-4b70-b7da-9db67510f909.png">

2. Contact us english
<img width="1359" alt="Screen Shot 2022-04-25 at 21 57 34" src="https://user-images.githubusercontent.com/13974474/165157048-e5a7e539-7c99-499a-a69f-d22d6d2c7b12.png">

3. Submit button on mobile not centered
<img width="416" alt="Screen Shot 2022-04-25 at 21 58 39" src="https://user-images.githubusercontent.com/13974474/165157108-394fad8e-530b-4921-a58c-92302e5ce3e9.png">

4. button shape and padding
<img width="195" alt="Screen Shot 2022-04-25 at 21 57 42" src="https://user-images.githubusercontent.com/13974474/165157171-d86c7c98-6583-495e-91f4-7e9d8c4dd444.png">

5. When clicking "Contact Us" link in header it scrolls and half of the form is out of screen.
<img width="1272" alt="Screen Shot 2022-04-25 at 22 24 55" src="https://user-images.githubusercontent.com/13974474/165159953-b07f14d2-ead0-4b6c-b9a0-f53668516ee5.png">

6. use semantic HTML!!!
You got a lot of `<h1>` this is not the way. The page should have one `<h1>`. each section title should have `<h2>`. Links should be `<a>` and not `<h1>`. use the correct semantic element for each task.

7. If you went and put in the effort into mobile navbar (which is nice). go ahead and close it when a language is chosen. also I would make the body non scrollable when the menu is open. Do you think the sliding menu can slide nicely with an animation instead of just popping up?

2022-04-25 19:40 UTC, omrirz commented on lib/interface.tsx
> +  contactUsFormErrorEmailInvalid: string
very nice!

2022-04-25 19:40 UTC, omrirz commented on components/footer.tsx
> +            {data.contactUsLinks.map((data) => (
contactUsLink would be a better name than "data"

2022-04-26 10:24 UTC, bendan7 commented
opsss most of the issues were in the last commit that I forgot to push.

2022-04-26 11:14 UTC, bendan7 commented
Hi Omri, first of all, I want to thank you for the code review, it's really not obvious these days.
Regarding the notes, I pushed the commit that I forgat which contains fixes for most of the issues and I added 1 more commit for the Btn issue in the ContactUsForm. regarding the RIGHT markups and the animation issues, I hope I will find the time in the next 2-3 to finish the task.

2022-04-26 11:27 UTC, omrirz commented
@bendan7 the animation is of lesser importance. The semantic HTML is CRITICAL! We build 100% accessible products. Nothing less.

2022-04-26 11:30 UTC, bendan7 commented
I didn't know that is so important, I will read about that. thanks

2022-04-26 16:07 UTC, bendan7 commented
@omrirz  All comments have been fixed

2022-04-28 15:35 UTC, omrirz requested changes

2022-04-28 15:35 UTC, omrirz commented on components/footer.tsx
> +              <h2 className={`cursor-pointer text-l `}>{menuLink.text}</h2>
This looks like a `<ul>` with `<li>` and Links. those are not headers.

2022-04-28 15:35 UTC, omrirz commented on components/Navigation.tsx
> +            <h2 className={`cursor-pointer text-xl ${className}`}>{text}</h2>
those are `<li>` and not `<h2>`

2022-04-28 15:35 UTC, omrirz commented on components/footer.tsx
> +          <h2 className="">
all the links together are an h2?

2022-04-28 15:35 UTC, omrirz commented on components/home-components/what-we-do.tsx
> +      <div className="grid gap-4 lg:grid-cols-4 md:grid-cols-2 sm:grid-cols-2 sm:gap-0">
use a `<ul>` and not just div everywhere.

2022-04-28 21:22 UTC, bendan7 commented on components/footer.tsx
> +          <h2 className="">
My bad, fixed

2022-04-28 21:25 UTC, bendan7 commented
@omrirz All comments have been fixed 

+ I Added on-hover animation to the Button component.

2024-08-25 17:42 UTC, closed without merging